include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/**.g.dart
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    - comment_references
    - directives_ordering
    - lines_longer_than_80_chars
    - prefer_single_quotes
    - require_trailing_commas
